const PROJECTS = [
  {
    id: 1,
    title: "MHL Market - Product Showcase",
    category: "Commercials",
    tags: ["E-commerce", "Social Media", "Motion Graphics"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    description: "Developed and launched a series of high-impact video ads for MHL Market's new product line, leading to a 40% increase in engagement. Managed the entire creative pipeline from concept to campaign launch.",
    client: "MHL Market",
    role: "Creative Lead & Ads Manager",
    tools: ["Adobe Premiere Pro", "Adobe After Effects", "Adobe Photoshop"],
    isFeatured: true,
  },
  {
    id: 2,
    title: "Luxury Villa Tour",
    category: "Real Estate",
    tags: ["Drone", "Cinematic", "Color Grading"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/ysz5S6PUM-U/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/ysz5S6PUM-U",
    description: "A cinematic walkthrough of a luxury property, utilizing smooth camera movements, drone footage, and expert color grading to highlight the architectural beauty and create an aspirational mood.",
    client: "HighEnd Properties",
    role: "Video Editor & Colorist",
    tools: ["DaVinci Resolve", "Adobe Premiere Pro"],
    isFeatured: true,
  },
  {
    id: 3,
    title: "Done - Social Reels Series",
    category: "Reels",
    tags: ["Fast-paced", "Trendy", "Social Media"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/2-crBg6wpp0/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/2-crBg6wpp0",
    description: "Produced a series of over 20 engaging, fast-paced reels for 'Done', focusing on trending audio and viral formats to boost brand visibility and audience interaction on Instagram and TikTok.",
    client: "Done",
    role: "Video Editor",
    tools: ["Adobe Premiere Pro"],
    isFeatured: true,
  },
  {
    id: 4,
    title: "AGN PRO - Podcast Highlights",
    category: "Vlogs",
    tags: ["Interview", "Multi-cam", "Social Media"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/9No-FiEInLA/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/9No-FiEInLA",
    description: "Edited multi-camera interview footage for AGN PRO's podcast series, creating compelling short-form clips for social media promotion and full-length episodes for YouTube.",
    client: "AGN PRO",
    role: "Multimedia Producer",
    tools: ["Adobe Premiere Pro"],
  },
  {
    id: 5,
    title: "AfriShop - E-commerce Ads",
    category: "Ads",
    tags: ["Product", "Conversion-focused", "E-commerce"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/J---aiyznGQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/J---aiyznGQ",
    description: "Created a suite of persuasive product commercials for AfriShop, an online store. The ads were optimized for various social platforms to drive conversions and sales.",
    client: "AfriShop",
    role: "Video Ads Creator",
    tools: ["Adobe After Effects", "Adobe Premiere Pro"],
  },
  {
    id: 6,
    title: "Desert Echoes - Short Film",
    category: "Cinematic",
    tags: ["Narrative", "Storytelling", "Color Grading"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/s3mw4_g565E/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/s3mw4_g565E",
    description: "A short cinematic piece telling a wordless story through powerful visuals and sound design. This project showcases narrative editing skills and advanced cinematic color grading techniques in DaVinci Resolve.",
    client: "Personal Project",
    role: "Director & Editor",
    tools: ["DaVinci Resolve", "Adobe After Effects"],
    isFeatured: true,
  },
  {
    id: 7,
    title: "CMC School - Water Pollution Reportage",
    category: "Cinematic",
    tags: ["Storytelling", "Stock Footage", "Educational"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/BLdRWqNaPZQ/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/BLdRWqNaPZQ",
    description: "An audio reportage for CMC school students about water pollution causes in Morocco. Used cinematic storytelling with stock footage to create an impactful and emotional presentation.",
    client: "CMC School",
    role: "Video Editor",
    tools: ["Adobe Premiere Pro"],
    isFeatured: true,
  },
  {
    id: 8,
    title: "Vlog Intro - Cinematic Re-edit",
    category: "Vlogs",
    tags: ["3D Animation", "Cinematic", "Intro"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/h7kgSuYjjwk/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/h7kgSuYjjwk",
    description: "A re-edit of a YouTube vlog intro for an editor application. Transformed a standard intro into a cinematic experience using 3D animations, cinematic music, and transitions.",
    client: "Vlog Channel (Test)",
    role: "Video Editor & Motion Graphics",
    tools: ["Adobe After Effects", "Adobe Premiere Pro"],
    isFeatured: true,
  },
  {
    id: 9,
    title: "Salon du Livre 2022 - Official Intro",
    category: "Commercials",
    tags: ["Motion Graphics", "Event", "Intro"],
    year: 2022,
    thumbnailUrl: "https://img.youtube.com/vi/4aEx0-3TS9k/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/4aEx0-3TS9k",
    description: "An intro created for the 2022 edition of the 'Salon du Livre' (Book Festival) during an internship with the national TV channel, Al Oula.",
    client: "Al Oula (SNRT)",
    role: "Motion Graphics Artist (Intern)",
    tools: ["Adobe After Effects"],
  },
  {
    id: 10,
    title: "Mhairafit - Gym Exercise Series",
    category: "Vlogs",
    tags: ["Fitness", "YouTube", "Series"],
    year: 2023,
    thumbnailUrl: "https://img.youtube.com/vi/SaUmmGj0gIs/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/SaUmmGj0gIs",
    description: "Filmed and edited a series of gym exercise videos for a YouTuber friend, focusing on clear demonstrations and an energetic pace.",
    client: "Mhairafit",
    role: "Filming & Video Editing",
    tools: ["Adobe Premiere Pro"],
  },
  {
    id: 11,
    title: "Brand Positioning Explained",
    category: "Reels",
    tags: ["Motion Graphics", "Educational", "Social Media"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/IrIZGsluMao/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/IrIZGsluMao",
    description: "A short motion graphics reel explaining the concept of brand positioning in a visually engaging format for social media.",
    client: "Personal Project",
    role: "Motion Graphics Artist",
    tools: ["Adobe After Effects"],
  },
  {
    id: 12,
    title: "English Vocabulary: Insects",
    category: "Reels",
    tags: ["Educational", "Language", "Social Media"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/-q53tbm6H-U/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/-q53tbm6H-U",
    description: "An educational reel teaching the names of insects in English, created for a language center to use on their social media platforms.",
    client: "Language Center",
    role: "Video Editor",
    tools: ["Adobe Premiere Pro"],
  },
  {
    id: 13,
    title: "Modern Motion Graphics Reel",
    category: "Reels",
    tags: ["Motion Graphics", "Fast-paced", "Social Media"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/qFa1Nwt2vck/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/qFa1Nwt2vck",
    description: "A fast-paced reel showcasing modern motion graphics skills and techniques, created with Adobe After Effects.",
    client: "Personal Project",
    role: "Motion Graphics Artist",
    tools: ["Adobe After Effects"],
  },
  {
    id: 14,
    title: "E-commerce Ad: The Organizer",
    category: "Ads",
    tags: ["E-commerce", "Product Ad", "Stock Footage"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/fdq24WLwZxs/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/fdq24WLwZxs",
    description: "A convincing ad for an e-commerce product. Sourced relevant stock footage and assembled a compelling narrative to highlight the product's benefits and drive sales.",
    client: "E-commerce Store",
    role: "Video Ads Creator",
    tools: ["Adobe Premiere Pro"],
    isFeatured: true,
  },
  {
    id: 15,
    title: "E-commerce Ad: Cloud Humidifier",
    category: "Ads",
    tags: ["E-commerce", "Product Ad", "Social Media"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/KAVuHSKlo2M/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/KAVuHSKlo2M",
    description: "A captivating short-form video ad for an e-commerce store, designed to highlight the Cloud Humidifier's features and drive conversions on social media.",
    client: "E-commerce Store",
    role: "Video Ads Creator",
    tools: ["Adobe Premiere Pro"],
  },
  {
    id: 16,
    title: "E-commerce Ad: Smart Cup",
    category: "Ads",
    tags: ["E-commerce", "Product Ad", "Conversion-focused"],
    year: 2024,
    thumbnailUrl: "https://img.youtube.com/vi/xcTFU5sXT3k/hqdefault.jpg",
    videoUrl: "https://www.youtube.com/embed/xcTFU5sXT3k",
    description: "A dynamic and persuasive video ad created for an e-commerce client to showcase a smart cup, resulting in increased product visibility and sales.",
    client: "E-commerce Store",
    role: "Video Ads Creator",
    tools: ["Adobe Premiere Pro"],
  }
];

const CATEGORIES = ["All", "Reels", "Commercials", "Real Estate", "Vlogs", "Cinematic", "Ads"];

const SERVICES = [
    { title: "Video Editing", icon: <FilmIcon /> },
    { title: "Motion Graphics", icon: <SparklesIcon /> },
    { title: "Ads Creation & Launch", icon: <ChartBarIcon /> },
    { title: "Photography", icon: <CameraIcon /> },
    { title: "Color Grading", icon: <PaintBrushIcon /> },
    { title: "Storytelling", icon: <StarIcon /> },
];

const CLIENTS = [
    { name: "Done", logoUrl: "https://tailwindui.com/img/logos/158x48/reform-logo-white.svg", caption: "Edited reels for Done" },
    { name: "MHL Market", logoUrl: "https://tailwindui.com/img/logos/158x48/transistor-logo-white.svg", caption: "Creative lead + ads for MHL Market" },
    { name: "AfriShop", logoUrl: "https://tailwindui.com/img/logos/158x48/tuple-logo-white.svg", caption: "Video ads for AfriShop" },
    { name: "SNRT", logoUrl: "https://tailwindui.com/img/logos/158x48/savvycal-logo-white.svg", caption: "Internship at Al Aoula" },
    { name: "Mhairafit", logoUrl: "https://tailwindui.com/img/logos/158x48/statamic-logo-white.svg", caption: "Filmed & edited gym series" },
    { name: "CMC School", logoUrl: "https://tailwindui.com/img/logos/158x48/statickit-logo-white.svg", caption: "Edited reportage on water pollution" },
];


const SKILLS = [
    { name: "Adobe Premiere Pro", level: 95 },
    { name: "Adobe After Effects", level: 90 },
    { name: "DaVinci Resolve", level: 85 },
    { name: "Adobe Photoshop", level: 90 },
];
